init:
  - git config --global core.autocrlf true
version: 1.0.{build}
image: Visual Studio 2017
test: on
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - dev
build_script:
- ps: .\build.ps1
